# Generated by Django 3.2.5 on 2021-08-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210819_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='username',
        ),
        migrations.AddField(
            model_name='event',
            name='username',
            field=models.ManyToManyField(to='home.Profile'),
        ),
    ]
