# Generated by Django 3.1.7 on 2021-08-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210819_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventimage',
            old_name='event',
            new_name='gelary',
        ),
        migrations.AddField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='home/images'),
        ),
    ]
