# Generated by Django 3.2.5 on 2021-09-11 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210910_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='username',
        ),
        migrations.AddField(
            model_name='event',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.profile'),
        ),
    ]
