# Generated by Django 3.2.5 on 2021-09-11 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210910_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.event')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.profile')),
            ],
        ),
    ]
