# Generated by Django 3.2.5 on 2021-09-11 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
